import type { Vaga } from "@/types/vagasType";


export const dataVagasMock: Vaga[] = [
  {
    id: "1",
    title: "Desenvolvedor Front-end Júnior",
    subscriptions: 20,
    createdAt: "2025-04-28T14:00:00Z",
    publicationPlataform: "Gupy",
    description: "Vaga para estudante com conhecimentos em React, HTML, CSS e JavaScript.",
    modalidade: "remoto",
    nível: "estágio",
  },
  {
    id: "2",
    title: "Analista de Dados",
    subscriptions: 4,
    createdAt: "2025-04-25T10:30:00Z",
    publicationPlataform: "LinkedIn",
    description: "É necessário conhecimento em Python, SQL e ferramentas de análise de dados.",
    modalidade: "remoto",
    nível: "efetivo",
  },
  {
    id: "3",
    title: "Engenheiro de Software",
    subscriptions: 2,
    createdAt: "2025-04-20T09:15:00Z",
    publicationPlataform: "Gupy | LinkedIn",
    description: "Desenvolvimento com Java ou Python, aplicação de boas práticas e padrões de projeto.",
    modalidade: "híbrido",
    nível: "efetivo",
  },
  {
    id: "4",
    title: "Desenvolvedor Mobile",
    subscriptions: 7,
    createdAt: "2025-04-22T11:45:00Z",
    publicationPlataform: "Kenoby",
    description: "Java, Swift ou Kotlin com foco em apps multiplataforma.",
    modalidade: "remoto",
    nível: "trainee",
  },
  {
    id: "5",
    title: "Desenvolvedor de Jogos",
    subscriptions: 12,
    createdAt: "2025-04-18T16:00:00Z",
    publicationPlataform: "Gupy",
    description: "Experiência com Unity, Unreal ou Godot. Conhecimento em lógica de programação e matemática.",
    modalidade: "presencial",
    nível: "estágio",
  },
  {
    id: "6",
    title: "Gerente de TI",
    subscriptions: 3,
    createdAt: "2025-04-15T08:20:00Z",
    publicationPlataform: "LinkedIn",
    description: "Coordenação de equipe técnica, gestão de infraestrutura e segurança da informação.",
    modalidade: "presencial",
    nível: "efetivo",
  },
];
